<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Cerberus.Agent.Service</AssemblyName>
    <RootNamespace>Cerberus.Agent.Service</RootNamespace>
    <ApplicationIcon>..\Assets\cerberus-favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cerberus.Agent.Runtime\Cerberus.Agent.Runtime.csproj" />
  </ItemGroup>
</Project>
