using System.Text;

namespace Cerberus.Agent.Integrations.Tailscale;

public static class TailscaleUpCommand
{
    public static string Build(string loginServer, string authKey)
    {
        _ = authKey;
        // Windows cmd friendly quoting. The generated debug helper intentionally does not
        // persist the auth key; support must provide it through an environment variable.
        var sb = new StringBuilder();
        sb.AppendLine("@echo off");
        sb.AppendLine("REM Generated by Cerberus agent (tailscale.ensure_connected).");
        sb.AppendLine("REM This file does not contain an auth key. Set CERBERUS_TAILSCALE_AUTHKEY before running.");
        sb.AppendLine("if \"%CERBERUS_TAILSCALE_AUTHKEY%\"==\"\" (");
        sb.AppendLine("  echo CERBERUS_TAILSCALE_AUTHKEY is required.");
        sb.AppendLine("  exit /b 2");
        sb.AppendLine(")");
        sb.AppendLine();
        sb.Append("tailscale up");
        sb.Append(" --login-server=");
        sb.Append('"').Append(loginServer.Replace("\"", "")).Append('"');
        sb.Append(" --authkey=");
        sb.Append("\"%CERBERUS_TAILSCALE_AUTHKEY%\"");
        sb.AppendLine();
        return sb.ToString();
    }
}
