using System.Text;

namespace Cerberus.Agent.Integrations.Tailscale;

public static class TailscaleUpCommand
{
    public static string Build(string loginServer, string authKey)
    {
        // Windows cmd friendly quoting. Auth keys can contain punctuation; keep them quoted.
        // We intentionally do not execute this automatically in some environments.
        var sb = new StringBuilder();
        sb.AppendLine("@echo off");
        sb.AppendLine("REM Generated by Cerberus agent (tailscale.ensure_connected).");
        sb.AppendLine("REM This file contains a sensitive auth key. Delete it after use.");
        sb.AppendLine();
        sb.Append("tailscale up");
        sb.Append(" --login-server=");
        sb.Append('"').Append(loginServer.Replace("\"", "")).Append('"');
        sb.Append(" --authkey=");
        sb.Append('"').Append(authKey.Replace("\"", "")).Append('"');
        sb.AppendLine();
        return sb.ToString();
    }
}
